version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-next-js-app
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - /app/public
      - /app/.next
      - /app/node_modules
    ports:
      - '3000:3000'
